### ISSUE TITLE
Map disabled on Fedora22

### ISSUE THREAD

**Issue by gbrennon** [Kismon/kismon#1]
Hey Kismon developers,

I'm trying to use Kismon to make some network analysis but the map function doesn't seem to be working.

Is there any dependency that I should be installing on my computer?

I'm using F22 x86_64

**Comment by dreadnought** [comment]
Hi,
the map in Kismon depends on the osm-gps-map package, unfortunately this package version is incompatible with Kismon version (0.6) in the latest fedora releases.

So please update Kismon to 0.7 or the latest git source.

``` bash
sudo yum remove kismon
sudo yum install osm-gps-map-gobject python3-simplejson
wget http://files.salecker.org/kismon/kismon-0.7.tar.gz
tar -xf kismon-0.7.tar.gz
cd kismon-0.7
sudo make install
```

The next problem that you will be hitting is that the OpenStreetMap Tiles will not show up and you will see a white background instead. More to read here:
http://comments.gmane.org/gmane.comp.genealogy.gramps.user/19823

To fix it you please set another map source than OpenStreetMap in the Kismon settings, e.g. opencyclemap.org, you can find other URLs here:
https://github.com/nzjrs/osm-gps-map/blob/1.0.1/src/osm-gps-map-source.c

Does this work for you?

**Comment by dreadnought** [comment]
There is now a compatible version of osm-gps-map (1.1.0) in Fedora.
https://apps.fedoraproject.org/packages/osm-gps-map/updates/
