### ISSUE TITLE
Installation Issues - KismetRest

### ISSUE THREAD

**Issue by kerbroasted** [Kismon/kismon#13]
I am having issues getting kismon to run with the latest version of kismet.

I have installed the KismetRest python module from https://github.com/kismetwireless/python-kismet-rest.git

But when I run kismon whilst kismet is running, I get the following:
Traceback (most recent call last):
  File "/usr/local/bin/kismon", line 2, in <module>
    import kismon.core
  File "/usr/local/lib/python3.7/dist-packages/kismon/core.py", line 39, in <module>
    from kismon.client_rest import *
  File "/usr/local/lib/python3.7/dist-packages/kismon/client_rest.py", line 33, in <module>
    import KismetRest
ModuleNotFoundError: No module named 'KismetRest'

I have also created a directory in my Kismet directory called /python_modules/ and placed the KismetRest module in there.

Can someone help please?

**Comment by dreadnought** [comment]
Hi,
did you install the KismetRest module for python3 (not python/python2)? Can you post the commands that you have executed?

**Comment by kerbroasted** [comment]
The following instructions dont seem to work:
$ git clone https://github.com/kismetwireless/kismet.git
$ cd kismet/python_modules/KismetRest
$ sudo python3 setup.py install

**Comment by kerbroasted** [comment]
To install kismon I have download the git repository and ran "sudo make install"

**Comment by r3vy** [comment]
I cant get it to work. There is no director for "kismet/python_modules/KismetRest",

**Comment by dreadnought** [comment]
For installing the Kismet Module please do this:
```
git clone https://github.com/kismetwireless/python-kismet-rest.git
cd python-kismet-rest
sudo python3 setup.py install
```
Then update the Kismon repository (`git pull`) and install it again. I applied changes to make it work with the latest Kismet Module.

**Comment by calidor** [comment]
KismetRest was renamed to kismet_rest so codechange is needed.

**Comment by dreadnought** [comment]
Yes, that is what I changed in https://github.com/Kismon/kismon/commit/68c22f40d643a78e7fc357f5d51978fe82e20530

**Comment by calidor** [comment]
then i think its fixed:) i pulled it just before you commited.
