### ISSUE TITLE
(Question) 20.04 repo osm-gps-map

### ISSUE THREAD

**Issue by alphafox02** [Kismon/kismon#17]
I was wondering it there’s any issues using the osm-gps-map build provided within the 20.04 repo vs the latest source. Everything with kismon appears to be working okay, but I noticed on the front page it looked as if kismon was requiring a newer version then what’s in the repo. 

Thank you.

**Comment by dreadnought** [comment]
As long as you don't experience issues it's fine to use the version 1.1.0 that is in Ubuntu 20.04. You can have a look at the [NEWS](https://github.com/nzjrs/osm-gps-map/blob/master/NEWS) file of osm-gps map to see which improvements were implemented in newer versions.

**Comment by alphafox02** [comment]
So far it seems good, but I do see what you mean about the updates. I’ll close and continue testing. Thank you.
