### ISSUE TITLE
Could not read the networks file after import.

### ISSUE THREAD

**Issue by krzotr** [Kismon/kismon#5]
Hi,

I imported networks from netxml file. When i opened the Kismon i got error message:

```
Could not read the networks file '/root/.kismon/networks.json':
Expecting ',' delimiter or '}': line 7837 column 116 (char 281860)
```

Line 7837:

```
"comment": "{'signal_dbm': {'min': -94, 'max': -65, 'last': -92}, 'lon': 19.460356, 'comment': {...}, 'ssid': "It's Over 9000!!!", 'manuf': 'Tp-LinkT', 'type': 'infrastructure', 'firsttime': 1455990834, 'cryptset': 736, 'servers': [], 'channel': 1, 'lasttime': 1455993387, 'lat': 51.754934}"
```

I see two problems:
1. network essid: **It's Over 9000!!!**
2. **'comment': {...}** - recursion, comment field contains comment

**Comment by dreadnought** [comment]
Hi,
this happened because of a bug in the import, which is fixed now. To get your file working again, you have to clear the failing "comment" lines in file by yourself or switch back to an older version of your networks.json file from ~/.kismon/.
