### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jackdneilson** [Kismon/kismon#8]
Exits while trying to find kismon.core

`Traceback (most recent call last):
  File "./kismon", line 2, in <module>
    import kismon.core
ModuleNotFoundError: No module named 'kismon'
`

**Comment by dreadnought** [comment]
Hey,
how do you get there? On which way have you installed kismon?

**Comment by jackdneilson** [comment]
Hi there,

That's the output I get when attempting to run the binary in the bin folder after cloning from the git repo.

**Comment by dreadnought** [comment]
The `bin/kismon` file is for installations and assumes that kismon module is installed on the system. You can execute `kismon/core.py` instead, it imports the module from the local directory.

**Comment by jackdneilson** [comment]
My mistake - I tried to run without building. Feel free to close :)
