### ISSUE TITLE
Feature Request: User configurable columns

### ISSUE THREAD

**Issue by NetworkJack2** [Kismon/kismon#9]
Can you make columns that are user selectable in either a menu or config so use can pick what columns they want to see.

It would also be great if the user could re-order columns

**Comment by dreadnought** [comment]
It is now possible to select the visible columns by right-clicking on the table header
![kismon-columns](https://user-images.githubusercontent.com/13079298/51090420-9df0e980-1773-11e9-8a29-4a2f54434f80.png)

**Comment by NetworkJack2** [comment]
f'ing awesome, you rock
